name: Docker Image CI

on:
  schedule:
    - cron: "0 23 15 * *"
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "*docker*" ]

jobs:
  build-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/news-please-ng:${GITHUB_REF##*/}$(date +%s)
            ${{ secrets.DOCKER_HUB_USERNAME }}/news-please-ng:latest



      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
